2021-05-29 23:50:18,488 ERROR: Exception on /index [GET] [in /home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py:1891
Traceback (most recent call last):
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/michael/Projects/InstroCommTool/app/main/routes.py", line 26, in index
    return render_template('index.html', title='Home', summary=summary)
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/michael/Projects/InstroCommTool/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/form.html' as wtf %}
  File "/home/michael/Projects/InstroCommTool/app/templates/base.html", line 55, in top-level template code
    {% block content %}
  File "/home/michael/Projects/InstroCommTool/app/templates/base.html", line 65, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/michael/Projects/InstroCommTool/app/templates/index.html", line 23, in block "app_content"
    <a style="color:#FFFFFF;" href="{{ url_for('main.new_group') }}">New Channel Group</a>
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.new_group'. Did you forget to specify values ['job_id']?
2021-05-30 00:00:56,079 INFO: InstroCommTool [in /home/michael/Projects/InstroCommTool/app/__init__.py:83
2021-05-30 00:00:58,348 ERROR: Exception on /index [GET] [in /home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py:1891
Traceback (most recent call last):
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/michael/Projects/InstroCommTool/app/main/routes.py", line 26, in index
    return render_template('index.html', title='Home', summary=summary)
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/michael/Projects/InstroCommTool/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/form.html' as wtf %}
  File "/home/michael/Projects/InstroCommTool/app/templates/base.html", line 55, in top-level template code
    {% block content %}
  File "/home/michael/Projects/InstroCommTool/app/templates/base.html", line 65, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/michael/Projects/InstroCommTool/app/templates/index.html", line 23, in block "app_content"
    <a style="color:#FFFFFF;" href="{{ url_for('main.new_group') }}">New Channel Group</a>
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.new_group'. Did you forget to specify values ['job_id']?
2021-05-30 00:01:41,328 INFO: InstroCommTool [in /home/michael/Projects/InstroCommTool/app/__init__.py:83
2021-05-30 00:02:56,366 INFO: InstroCommTool [in /home/michael/Projects/InstroCommTool/app/__init__.py:83
2021-05-30 00:05:18,196 INFO: InstroCommTool [in /home/michael/Projects/InstroCommTool/app/__init__.py:83
2021-05-30 00:07:03,894 INFO: InstroCommTool [in /home/michael/Projects/InstroCommTool/app/__init__.py:83
2021-05-30 00:08:29,905 INFO: InstroCommTool [in /home/michael/Projects/InstroCommTool/app/__init__.py:83
2021-05-30 00:09:46,780 INFO: InstroCommTool [in /home/michael/Projects/InstroCommTool/app/__init__.py:83
