2021-04-24 20:21:48,669 ERROR: Exception on /channel_list [GET] [in /home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py:1891
Traceback (most recent call last):
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/michael/Projects/InstroCommTool/app/main/routes.py", line 168, in channel_list
    return render_template('channel_list.html', title='Channel List', channel_group_form=channel_group_form, units_dict=ENG_UNITS,
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/michael/Projects/InstroCommTool/app/templates/channel_list.html", line 2, in top-level template code
    {% import 'bootstrap/form.html' as wtf %}
  File "/home/michael/Projects/InstroCommTool/app/templates/base.html", line 43, in top-level template code
    {% block content %}
  File "/home/michael/Projects/InstroCommTool/app/templates/base.html", line 53, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/michael/Projects/InstroCommTool/app/templates/channel_list.html", line 24, in block "app_content"
    {% include '_testpoint.html' %}
  File "/home/michael/Projects/InstroCommTool/app/templates/_testpoint.html", line 21, in top-level template code
    {{ print(item) }}
jinja2.exceptions.UndefinedError: 'print' is undefined
2021-04-24 20:23:21,051 INFO: InstroCommTool [in /home/michael/Projects/InstroCommTool/app/__init__.py:83
2021-04-24 20:23:22,939 ERROR: Exception on /channel_list [GET] [in /home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py:1891
Traceback (most recent call last):
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/michael/Projects/InstroCommTool/app/main/routes.py", line 172, in channel_list
    return render_template('channel_list.html', title='Channel List', channel_group_form=channel_group_form, units_dict=ENG_UNITS,
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/michael/Projects/InstroCommTool/app/templates/channel_list.html", line 2, in top-level template code
    {% import 'bootstrap/form.html' as wtf %}
  File "/home/michael/Projects/InstroCommTool/app/templates/base.html", line 43, in top-level template code
    {% block content %}
  File "/home/michael/Projects/InstroCommTool/app/templates/base.html", line 53, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/michael/Projects/InstroCommTool/app/templates/channel_list.html", line 24, in block "app_content"
    {% include '_testpoint.html' %}
  File "/home/michael/Projects/InstroCommTool/app/templates/_testpoint.html", line 20, in top-level template code
    {{ channel_item.channel_form.testpoints.input_val(placeholder=testpoint_item.input_val_nom) }}
jinja2.exceptions.UndefinedError: 'wtforms.fields.core.FieldList object' has no attribute 'input_val'
2021-04-24 20:23:39,513 INFO: InstroCommTool [in /home/michael/Projects/InstroCommTool/app/__init__.py:83
2021-04-24 20:23:40,789 ERROR: Exception on /channel_list [GET] [in /home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py:1891
Traceback (most recent call last):
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/michael/Projects/InstroCommTool/app/main/routes.py", line 172, in channel_list
    return render_template('channel_list.html', title='Channel List', channel_group_form=channel_group_form, units_dict=ENG_UNITS,
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/michael/Projects/InstroCommTool/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/michael/Projects/InstroCommTool/app/templates/channel_list.html", line 2, in top-level template code
    {% import 'bootstrap/form.html' as wtf %}
  File "/home/michael/Projects/InstroCommTool/app/templates/base.html", line 43, in top-level template code
    {% block content %}
  File "/home/michael/Projects/InstroCommTool/app/templates/base.html", line 53, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/michael/Projects/InstroCommTool/app/templates/channel_list.html", line 24, in block "app_content"
    {% include '_testpoint.html' %}
  File "/home/michael/Projects/InstroCommTool/app/templates/_testpoint.html", line 20, in top-level template code
    {{ channel_item.channel_form.testpoints.input_val(placeholder=testpoint_item.input_val_nom) }}
jinja2.exceptions.UndefinedError: 'wtforms.fields.core.FieldList object' has no attribute 'input_val'
2021-04-24 20:24:50,131 INFO: InstroCommTool [in /home/michael/Projects/InstroCommTool/app/__init__.py:83
